name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install, build, test and lint
      run: |
        yarn install --frozen-lockfile --non-interactive
        yarn build
        yarn test -c=ci
        yarn lint
        npm i -g codecov
        codecov --disable=gcov -f dist/coverage/ng-log-facebook-analytics/lcov.info -F unit
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
